dataset: cifar10
model:
  name: vit-tiny
  kind: standard
training_arguments:
  epochs: 250
  batch_size: 128
  base_learning_rate: 1e-4
  optimizer:
    kind: adam
    hparams:
      weight_decay: 1e-7
  augmentation:
    - random_crop
    - color_jitter
    - horizontal_flip
    - cutout