dataset: cifar10
model:
  name: baseline
  kind: standard
  layer:
    conv1:
      layer_type: conv2d
      hparams:
        filters: 256
        kernel_size: [ 5, 5 ]
        strides: [ 1, 1 ]
        activation: relu
    conv2:
      layer_type: conv2d
      hparams:
        filters: 256
        kernel_size: [ 5, 5 ]
        strides: [ 1, 1 ]
        activation: relu
    conv3:
      layer_type: conv2d
      hparams:
        filters: 128
        kernel_size: [ 5, 5 ]
        strides: [ 1, 1 ]
        activation: relu
    flatten:
      layer_type: flatten
    fc1:
      layer_type: dense
      hparams:
        units: 328
        activation: relu
    fc2:
      layer_type: dense
      hparams:
        units: 192
        activation: relu
    dropout:
      layer_type: dropout
      hparams:
        rate: 0.5
    classifier:
      layer_type: dense
      hparams:
        units: 10
training_arguments:
  epochs: 250
  batch_size: 128
  base_learning_rate: 1e-5
  optimizer:
    kind: adam
    hparams:
      weight_decay: 1e-7
  augmentation:
    - random_crop
    - color_jitter
    - horizontal_flip
    - cutout
