dataset: cifar10
model:
  name: vit-tiny
  kind: standard
training_arguments:
  epochs: 10
  batch_size: 128
  base_learning_rate: 1e-5
  optimizer:
    kind: adam
    hparams:
      weight_decay: 1e-5
